### ISSUE TITLE
Ei hae uusia palautteita joissa 2022-2023 merkintä?

### ISSUE THREAD

**Issue by headman78** [PetriAsi/ArvoApi#2]
Alkuun kiitokset tästä skriptistä! Huomasin että se ei hae Arvo järjestelmään tulleita uusia palautteita. Siellä on 3 uutta jotka tunnistaa lopussa olevasta 2022-2023 vuodesta, esim. "Opiskelijapalaute - ammatillisen tutkinnon osan tai osia suorittaneet 2022-2023"

Onko tiedossa oleva vika?

**Comment by PetriAsi** [comment]
Ainakin meillä näkyy seuraavat tiedostot 2022-2023 kansioissa alla pari esimerkkiä:
Tutkinnon aloittaneista
![image](https://user-images.githubusercontent.com/8735148/186758243-ce96d655-0259-44e3-8537-dccfec43adbf.png)
ja tutkinnon suorittaneista
![image](https://user-images.githubusercontent.com/8735148/186758306-7461dfc6-8649-48e1-8914-f1910460ec55.png)

Tuohon viimeisempään ei muodostu vastaustiedostoja, koska scripti vertaa tallennettujen metatietojen pohjalta onko  kyselyyn tullut uusia vastauksia viimeisen haun jälkeen.

Poistamalla tallennuskansiosta tiedostot tallennetut.json tallennetut.xml voit pakoittaa scriptin hakemaan kaikki saatavilla olevat tiedostot uudelleen.

**Comment by headman78** [comment]
Kiitos vastauksesta, kokeilempa tuota. Löysin ainoastaan tuon xml-tiedoston, jsonia ei ollut.

**Comment by PetriAsi** [comment]
Tarkistitko arvo-palvelusta että vastauksia noihin uusiin kyselyihin on jo tullut?

**Comment by headman78** [comment]
Ei auttanut tallennetut.xml:än poisto. Tiedostossa on kyllä mainintoja näistä 2022-2023, mutta mitään dataa se ei hae:
![image](https://user-images.githubusercontent.com/13760604/186902883-403d55f7-3255-4ba1-81b7-e2e56544c679.png)

**Comment by PetriAsi** [comment]
Hmmm... Jos kokeilet sillä tunnuksella jota scripti käyttää, kirjautua arvo-palveluun. Meillä muistaakseni oli kerran käynyt niin että palvelussa odotti salasanan vaihtopyyntö tms.. joka esti scriptin toiminnan.

Ja tuon jälkeen vielä muutama juttu vielä jolla voi haarukoida ongelmaa.
Päivittyvätkö muut tiedostot normaalisti?
Jos ajat scriptin käsin päätteessä, kiroileeko se joitain?

**Comment by headman78** [comment]
Sain skriptin toimimaan, olin muokannut $saveTo muuttujaa ("D:\Arvo2CSV\Arvosta") että sain sen toimimaan task schedulerin kautta ajettuna. Vaihdoin sen nyt muotoon ".\Arvosta" niin nyt se hakee myös nämä 2022-2023 loppuiset.

**Comment by PetriAsi** [comment]
Hyvä että selkis!
